import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { NativeFeishuTransport, NativeFeishuWsInbound } from "./feishu-native.js";
const credentials = { appId: "cli_x", appSecret: "secret", brand: "feishu" as const, updatedAt: 1 };
describe("NativeFeishuTransport", () => {
 it("发送文本并返回真实 message_id", async () => { let input: any; const t = new NativeFeishuTransport(credentials, { userId: "ou_owner", client: { im: { message: { create: async (v: unknown) => { input = v; return { data: { message_id: "om_1" } }; } } } } }); assert.deepEqual(await t.send({ title: "标题", body: "正文" }), { messageId: "om_1" }); assert.equal(input.params.receive_id_type, "open_id"); assert.equal(input.data.receive_id, "ou_owner"); });
 it("未绑定主人时关闭发送，setRecipient 后立即可发", async () => { const t = new NativeFeishuTransport(credentials, { client: { im: { message: { create: async () => ({ data: { message_id: "om_pair" } }) } } } }); await assert.rejects(() => t.send({ body: "x" }), /lark/); t.setRecipient({ userId: "ou_new" }); assert.equal((await t.send({ body: "x" })).messageId, "om_pair"); });
 it("WS fixture 解析并在 stop 时关闭 SDK", async () => { let closed = false; let received = ""; const ws = { start: async () => {}, getConnectionStatus: () => ({ state: "connected" as const }), close: () => { closed = true; } }; const inbound = new NativeFeishuWsInbound(credentials, { onMessage: async (input) => { received = `${input.openId}:${input.text}`; return { ok: true, reply: "" }; } }, { ws, dispatcher: {} }); await inbound.start(); await inbound.accept({ event: { sender: { sender_id: { open_id: "ou_x" } }, message: { content: JSON.stringify({ text: "你好" }) } } }); assert.equal(received, "ou_x:你好"); inbound.stop(); assert.equal(closed, true); });
 it("SDK start 返回但未连接时，等待真实连接并超时", async () => { const ws = { start: async () => {}, getConnectionStatus: () => ({ state: "connecting" as const }), close: () => {} }; const inbound = new NativeFeishuWsInbound(credentials, { onMessage: async () => ({ ok: true, reply: "" }) }, { ws, dispatcher: {}, readyTimeoutMs: 10, readyPollMs: 1 }); await assert.rejects(() => inbound.start(), /就绪超时/); });
 it("连接状态变为 connected 后才报告就绪", async () => { let calls = 0; const ws = { start: async () => {}, getConnectionStatus: () => ({ state: (calls++ > 1 ? "connected" : "connecting") as "connected" | "connecting" }), close: () => {} }; const inbound = new NativeFeishuWsInbound(credentials, { onMessage: async () => ({ ok: true, reply: "" }) }, { ws, dispatcher: {}, readyTimeoutMs: 100, readyPollMs: 1 }); await inbound.start(); });
});
